MonthlyBudget/Controllers/BudgetController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MonthlyBudget.Models;
using MonthlyBudget.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using MonthlyBudget.Models.ViewModels;

namespace MonthlyBudget.Controllers
{
    public class BudgetController:Controller
    {
        private ICategorySvc _categories;
        private IBudgetItemSvc _budgets;
       // private IPurchaseSvc _purchases;

        public BudgetController(ICategorySvc categories, IBudgetItemSvc budgets)
        {
            _categories = categories;
            _budgets = budgets;
            //_purchases = purchases;
        }

        // ******************* BUDGETS ******************
        [HttpGet]
        [Authorize]
        public IActionResult Index(string err, int? m, int? y)
        {
            var ViewModel = new BudgetViewModel();

            ViewModel.Categories = _categories.FindAll(User.Identity.Name);
            ViewModel.Categories.Sort();

            if (m.HasValue)
                ViewModel.BudgetMonth = (int)m;
            else
                ViewModel.BudgetMonth = DateTime.Now.Month;

            if (y.HasValue)
                ViewModel.BudgetYear = (int)y;
            else
                ViewModel.BudgetYear = DateTime.Now.Year;

            ViewModel.BudgetItems = _budgets.FindAll(User.Identity.Name, ViewModel.BudgetMonth, ViewModel.BudgetYear);
            ViewModel.BudgetItems = ViewModel.BudgetItems.OrderBy(x => x.Category).ToList();
            int TotalBudgetedAmount = 0;
            foreach (var b in ViewModel.BudgetItems)
            {
                TotalBudgetedAmount += b.Amount;
            }
            ViewModel.BudgetItems.Add(new BudgetItem { Category = "Total", Amount=TotalBudgetedAmount});

            ViewBag.Err = err;

            return View(ViewModel);// new BudgetItem { Year = Year, Month = Month }); 
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult Index(BudgetViewModel bud)
        {
            var Budget = new BudgetItem
            {
                Amount = bud.Amount,
                BudgetMonth = bud.BudgetMonth,
                BudgetYear = bud.BudgetYear,
                User = User.Identity.Name,
                Category = bud.Category
            };

            if (ModelState.IsValid && !_budgets.Exists(Budget))
            {
                _budgets.Add(Budget);
                _budgets.Commit();
                return RedirectToAction("Index", new { m = bud.BudgetMonth, y = bud.BudgetYear });//, new { m = bud.Month, y = bud.Year });
            }
            else
            {
                return RedirectToAction("Index", new { m = bud.BudgetMonth, y = bud.BudgetYear,
                                                        err = "Category already exists for this month." });
            }
        }

        // ******************* DELETES ******************
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteBudget(BudgetItem bud)
        {
            var budget = new BudgetItem
            {
                User = User.Identity.Name,
                BudgetMonth = bud.BudgetMonth,
                BudgetYear = bud.BudgetYear,
                Category = bud.Category
            };
            if (_budgets.Remove(budget) == true)
            {
                _budgets.Commit();
                return RedirectToAction("Index", new { m = bud.BudgetMonth, y = bud.BudgetYear });
            }
            else
            {
                return RedirectToAction("Index", new { err = "Unable to remove item", m=bud.BudgetMonth, y=bud.BudgetYear });
            }
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public IActionResult CopyLastMonth(int BudgetMonth, int BudgetYear)
        {
            // figure out 'last month/yr'
            int lastMonth, lastYear;

            if (BudgetMonth == 1)
            {
                lastMonth = 12;
                lastYear = BudgetYear -1;
            }
            else
            {
                lastMonth = BudgetMonth - 1;
                lastYear = BudgetYear;
            }

            var lastMonthsBudget = _budgets.FindAll(User.Identity.Name, lastMonth, lastYear);
            var thisMonthsBudget = _budgets.FindAll(User.Identity.Name, BudgetMonth, BudgetYear);

            if (lastMonthsBudget.Count == 0) { return RedirectToAction("Index", new { err = "No budget for last month!", m=BudgetMonth,
                                                                        y=BudgetYear}); }

            // first delete this month's budget
            foreach (var b in thisMonthsBudget)
            {
                _budgets.Remove(new BudgetItem {Category=b.Category, Amount=b.Amount, User=User.Identity.Name,
                                                BudgetMonth = b.BudgetMonth, BudgetYear=b.BudgetYear});
            }

            // then copy last month's budget to this month's
            foreach (var b in lastMonthsBudget)
            {
                _budgets.Add(new BudgetItem { Category = b.Category, Amount=b.Amount, User = User.Identity.Name, BudgetYear = BudgetYear,
                                            BudgetMonth = BudgetMonth});
                
            }
            _budgets.Commit();
            return RedirectToAction("Index", new { m=BudgetMonth, y=BudgetYear});
        }

    }
}

MonthlyBudget/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using MonthlyBudget.Models.ViewModels;
using MonthlyBudget.Services;

namespace MonthlyBudget.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {   // Dependency injection
        private ICategorySvc _categories;

        private IPurchaseSvc _purchases;

        public ReportController(ICategorySvc categories, IPurchaseSvc purchases)
        {
            _categories = categories;
            _purchases = purchases;
        }

        [HttpGet]
        public IActionResult Index(string err)
        {
            var viewModel = new AllPurchaseViewModel
            {
                Categories = _categories.FindAll(User.Identity.Name),
                ToDate = DateTime.Now.ToString("MM/dd/yyyy"),
                FromDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1).ToString("MM/dd/yyyy")
            };
            viewModel.Categories.Add("*");
            viewModel.Categories.Sort();
            if (err != "")
            {
                ViewBag.err = err;
            }

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(string ToDate, string FromDate, string Category)
        {
            var viewModel = new AllPurchaseViewModel();

            if (DateTime.TryParse(ToDate, out DateTime ToDt) && DateTime.TryParse(FromDate, out DateTime FromDt) && 
                ToDt  > FromDt)
            {
                viewModel.Categories = _categories.FindAll(User.Identity.Name); // duplicate code, lazy
                if (Category == "*")
                {
                    viewModel.Purchases = _purchases.FindAllByDateRange(FromDt, ToDt, User.Identity.Name);
                }
                else
                {
                    if (viewModel.Categories.Contains(Category))
                    {
                        viewModel.Purchases = _purchases.FindByCategoryAndDateRange(FromDt, ToDt, Category, User.Identity.Name);
                    }
                    else
                    {
                        return RedirectToAction("Index", new { err = "Invalid category" });
                    }
                    
                }
            }
            else
            {
                //dates are in bad format...redirect with error msg
                return RedirectToAction("Index", new { err="Invalid dates" });
            }

            viewModel.FromDate = FromDate;
            viewModel.ToDate = ToDate;
            
            viewModel.Categories.Add("*");
            viewModel.Categories.Sort();

            foreach(var p in viewModel.Purchases)
            {
                viewModel.Total += p.Cost;
            }

            return View(viewModel);
        }
    }
}

MonthlyBudget/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MonthlyBudget</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/siteOverrides.css" />
        <link rel="stylesheet" href="~/css/home.css" />
        <link rel="stylesheet" href="~/css/login.css" />
        <link rel="stylesheet" href="~/css/budget.css" />
        <link rel="stylesheet" href="~/css/category.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
    <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MonthlyBudget</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Purchase" asp-action="Index">Add Purchase</a></li>
                    <li><a asp-area="" asp-controller="Budget" asp-action="Index">Create Budget</a></li>
                    <li><a asp-area="" asp-controller="Report" asp-action="Index">View Reports</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MonthlyBudget</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>